### ISSUE TITLE
设置了最大宽度或者最小宽度后页面样式就炸了

### ISSUE THREAD

**Issue by BeiJiu123** [wangguangyou/postcss-px-to-clamp#2]
module.exports = {
	plugins: [
		require("postcss-px-to-clamp")({
			viewportWidth: 1920,
			viewportUnit: "vw",
			fontViewportUnit: "vw",
			maxViewportWidth: 1920,
			minViewportWidth: 1200,
			unitPrecision: 5,
			selectorBlackList: [],
			propBlackList: [],
			minPixelValue: 1,
			mediaQuery: false,
			keyframesQuery: false,
			replace: true,
			exclude: undefined,
			include: undefined
		})
	]
};

**Comment by wangguangyou** [comment]
string类型 带单位。

**Comment by wswmsword** [comment]
@BeiJiu123 

```diff
module.exports = {
plugins: [
  require("postcss-px-to-clamp")({
    viewportWidth: 1920,
    viewportUnit: "vw",
    fontViewportUnit: "vw",
-   maxViewportWidth: 1920,
+   maxViewportWidth: "1920px",
-   minViewportWidth: 1200,
+   minViewportWidth: "1200px",
    unitPrecision: 5,
    selectorBlackList: [],
    propBlackList: [],
    minPixelValue: 1,
    mediaQuery: false,
    keyframesQuery: false,
    replace: true,
    exclude: undefined,
    include: undefined
  })
  ]
};
```

**Comment by BeiJiu123** [comment]
有什么办法可以解决容器缩小后字体到了最小字体后不能在继续缩小吗
![image](https://github.com/wangguangyou/postcss-px-to-clamp/assets/74284601/0c9ee849-4782-4ffd-ad2e-3a5538370f1b)
![image](https://github.com/wangguangyou/postcss-px-to-clamp/assets/74284601/7f8daeda-5332-48f3-8eab-0cef57639bdf)

**Comment by wangguangyou** [comment]
> 有什么办法可以解决容器缩小后字体到了最小字体后不能在继续缩小吗 ![image](https://user-images.githubusercontent.com/74284601/275387293-0c9ee849-4782-4ffd-ad2e-3a5538370f1b.png) ![image](https://user-images.githubusercontent.com/74284601/275387476-7f8daeda-5332-48f3-8eab-0cef57639bdf.png)

你需要调高minViewportWidth的值
